// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserServiceAPI.Models;

#nullable disable

namespace UserServiceAPI.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20250905101927_Add1")]
    partial class Add1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserServiceAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john.doe@example.com",
                            FullName = "John Doe",
                            Position = "Developer"
                        },
                        new
                        {
                            Id = 2,
                            Email = "jane.smith@example.com",
                            FullName = "Jane Smith",
                            Position = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            Email = "sara.taylor@example.com",
                            FullName = "Sara Taylor",
                            Position = "Manager"
                        },
                        new
                        {
                            Id = 4,
                            Email = "pam.jordon@example.com",
                            FullName = "Pam Jordon",
                            Position = "Developer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
