// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResponseCaching.Data;

#nullable disable

namespace ResponseCaching.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ResponseCaching.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 8, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Product A Description",
                            ModifiedDate = new DateTime(2025, 8, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Product A",
                            Price = 10.0m
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 8, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Product B Description",
                            ModifiedDate = new DateTime(2025, 8, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Product B",
                            Price = 20.0m
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 8, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Product C Description",
                            ModifiedDate = new DateTime(2025, 8, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Product C",
                            Price = 30.0m
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 8, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Product D Description",
                            ModifiedDate = new DateTime(2025, 8, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Product D",
                            Price = 40.0m
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 8, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Product E Description",
                            ModifiedDate = new DateTime(2025, 8, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Product E",
                            Price = 50.0m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
